# Generated by Django 5.0.6 on 2024-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_fotografia_user_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
